j30nj33hy3/plzSeatdown

plzSeatdown/src/main/webapp/WEB-INF/views/kkk.html
=> 2020.03.06 14:55 강정임 test

plzSeatdown/src/main/webapp/WEB-INF/views/sw.html
=> 20/03/06 14시 55분 양서원 html 파일 올림

plzSeatdown/src/main/webapp/WEB-INF/views/JEH.html
=> 2020.03.06 14:55 조은희 테스트

plzSeatdown/src/main/webapp/WEB-INF/views/Yuri.html
=> 2020.03.06 14:55 최유리 테스트

plzSeatdown/src/main/webapp/WEB-INF/views/희빈.html
=> 2020.03.06 14:56 윤희빈 테스트

plzSeatdown/src/main/webapp/WEB-INF/views/JJH.html
2020.03.06 15:12 전지혜 TEST
통합본으로 Pull Request
=> 2020.03.06 15:12 전지혜 TEST

plzSeatdown/src/main/webapp/WEB-INF/views/common/nav.jsp
2020.03.06 17:38 전지혜 nav.jsp 수정
=> 2020.03.06 17:38 전지혜 nav.jsp 수정

plzSeatdown/src/main/webapp/WEB-INF/views/test.html
2020.03.06 17:56 전지혜 test.html
=> 2020.03.06 17:56 전지혜 test.html

plzSeatdown/src/main/webapp/WEB-INF/views/admin/show.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/theater.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/review_seats.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/review_show.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/review_theater.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/review_write.jsp, plzSeatdown/src/main/webapp/resources/css/review_seats.css, plzSeatdown/src/main/webapp/resources/css/review_show.css, plzSeatdown/src/main/webapp/resources/css/review_theater.css, plzSeatdown/src/main/webapp/resources/css/review_write.css, plzSeatdown/src/main/webapp/show.jsp
20200309 08:57 강정임 jsp 및 css 업로드
됐으면 좋겠다,,, 작은 바램,,,
=> 20200309 08:57 강정임 jsp 및 css 업로드

plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java
memberController 관리자페이지 이동 부분 삭제
=> 2020.03.09 16:45 강정임

plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminController.java, plzSeatdown/src/main/webapp/WEB-INF/views/common/nav.jsp
admin으로 로그인 시 nav의 mypage를
Admin으로 뜨게하여 클릭 시 관리자페이지로 이동하게 함
=> 2020.03.09 17:15 양서원

plzSeatdown/src/main/webapp/WEB-INF/views/common/nav.jsp
=> 2020.03.11 15:58 강정임 nav.jsp 수정

plzSeatdown/pom.xml, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/dao/MemberDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/service/MemberService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/service/MemberServiceImpl.java, plzSeatdown/src/main/resources/mappers/member-mapper.xml, plzSeatdown/src/main/resources/spring/root-context.xml, plzSeatdown/src/main/webapp/WEB-INF/views/member/emailCheckForm.jsp
=> 2020.03.14 최유리

plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminCommController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/dao/AdminCommDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/dao/AdminReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminCommService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminCommServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminReivewServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminReviewService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/vo/AdminCommunity.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/vo/AdminReview.java, plzSeatdown/src/main/resources/mappers/admin-community-mapper.xml, plzSeatdown/src/main/resources/mappers/admin-review-mapper.xml, plzSeatdown/src/main/resources/mybatis-config.xml, plzSeatdown/src/main/webapp/WEB-INF/views/admin/common/nav.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/community/communityList.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/review/reviewList.jsp
=> 2020.03.15 관리자 게시판 커뮤니티, 리뷰 게시판 구성

plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminShowController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminTheaterController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/dao/AdminShowDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/dao/AdminTheaterDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminShowService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminShowServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminTheaterService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminTheaterServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/controller/APIController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/dao/APIDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/dao/TheaterAPIDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/service/APIService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/service/APIServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/vo/Show.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/vo/Theater.java, plzSeatdown/src/main/resources/mappers/admin-show-mapper.xml, plzSeatdown/src/main/resources/mappers/admin-theater-mapper.xml, plzSeatdown/src/main/resources/mappers/api-mapper.xml, plzSeatdown/src/main/resources/mybatis-config.xml, plzSeatdown/src/main/webapp/WEB-INF/views/admin/common/nav.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/show.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/theater.jsp
api controller 및 model 작성
admin/theater,show controller 및 model 작성
admin/theater.jsp, show.jsp 수정
=> 2020.03.16 17:23 강정임

plzSeatdown/src/main/java/com/bg/plzSeatdown/api/controller/APIController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/dao/APIDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/service/APIService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/service/APIServiceImpl.java, plzSeatdown/src/main/resources/mappers/api-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/admin/show.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/theater.jsp
관리자 api controller 및 model 수정(Theater, Show 테이블 업데이트 가능)
관리자 theater.jsp show.jsp 수정
=> 2020.03.16 18:48 강정임

plzSeatdown/pom.xml, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/dao/MemberDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/service/MemberService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/service/MemberServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/vo/Member.java, plzSeatdown/src/main/resources/mappers/member-mapper.xml, plzSeatdown/src/main/resources/spring/appServlet/servlet-context.xml, plzSeatdown/src/main/webapp/WEB-INF/views/member/emailCheckForm.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/findIdPwd.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/findIdResult.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/findPwdAuthForm.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/resetPwdForm.jsp, plzSeatdown/src/main/webapp/resources/css/member-emailCheck.css, plzSeatdown/src/main/webapp/resources/css/member-findIdPwd.css, plzSeatdown/src/main/webapp/resources/css/member-findIdPwdResult.css, plzSeatdown/src/main/webapp/resources/css/member-pwdAuthForm.css, plzSeatdown/src/main/webapp/resources/css/member-resetPwd.css
=> 2020.03.19 최유리 아이디/비밀번호 찾기 test용

plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java
=> 2020.03.19 ip주소 변경

plzSeatdown/src/main/java/com/bg/plzSeatdown/api/controller/APIController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/dao/APIDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/service/APIService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/service/APIServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/vo/Show.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/DAO/ReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/vo/Show.java, plzSeatdown/src/main/resources/mappers/admin-theater-mapper.xml, plzSeatdown/src/main/resources/mappers/api-mapper.xml, plzSeatdown/src/main/resources/mappers/review-mapper.xml, plzSeatdown/src/main/resources/mybatis-config.xml, plzSeatdown/src/main/webapp/WEB-INF/views/admin/show.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/theater.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewTheater.jsp, plzSeatdown/src/main/webapp/resources/css/review_theater.css
Theater 테이블 수정으로 인한
API Controller, model 수정
Admin show/theater Controller, model 수정
Review Controller, model 수정
=> 2020.03.20 12:14 강정임

plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminTheaterController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/dao/AdminTheaterDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminTheaterService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/service/AdminTheaterServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/model/vo/TheaterLogo.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/controller/APIController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/api/model/vo/Theater.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/resources/mappers/admin-theater-mapper.xml, plzSeatdown/src/main/resources/mybatis-config.xml, plzSeatdown/src/main/webapp/WEB-INF/views/admin/theater.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewShow.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewTheater.jsp, plzSeatdown/src/main/webapp/resources/css/review_seats.css
=> 2020.03.21 13:39 강정임

plzSeatdown/src/main/java/com/bg/plzSeatdown/community/controller/CommunityController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/community/model/dao/CommunityDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/community/model/service/CommunityService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/community/model/service/CommunityServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/community/model/vo/Community.java, plzSeatdown/src/main/resources/mappers/yhb-community-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/community/communityDetail.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/community/communityInsert.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/community/communityList.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/community/communityUpdate.jsp
=> 2020.03.23 17:38 윤희빈 커뮤니티 이전,다음 추가

plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/controller/MypageController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/model/dao/MypageDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/model/service/MypageService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/model/service/MypageServiceImpl.java, plzSeatdown/src/main/resources/mappers/mypage-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/askDetail.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/changePwd.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/mycommu.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/mypage.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/myreview.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/myticket.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/secession.jsp, plzSeatdown/src/main/webapp/resources/css/mypage_mycommu.css
=> 2020.03.24 20:13 마이커뮤 추가

plzSeatdown/pom.xml, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminCommController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/websocket/common/EchoHandler.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/websocket/controller/WebChattingController.java, plzSeatdown/src/main/resources/spring/appServlet/servlet-context.xml, plzSeatdown/src/main/webapp/WEB-INF/views/chat/chattingView.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/common/nav.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/index2.jsp, plzSeatdown/src/main/webapp/resources/css/chat.css
=> 2020.03.25 서원

plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/DAO/ReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/vo/SeatReview.java, plzSeatdown/src/main/resources/mappers/review-mapper.xml, plzSeatdown/src/main/resources/mybatis-config.xml, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp
=> 2020.03.25 최유리 좌석리뷰상세 작업중

plzSeatdown/src/main/webapp/WEB-INF/views/community/communityDetail.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/community/communityList.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/notice/noticeList.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/qna/qnaList.jsp, plzSeatdown/src/main/webapp/resources/css/boardcss.css
=> 2020.03.25 10:40 윤희빈 - 커뮤니티, 공지, qna jsp파일 수정 (페이징)

plzSeatdown/src/main/java/com/bg/plzSeatdown/community/controller/CommunityController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/community/model/vo/Community.java, plzSeatdown/src/main/resources/mappers/yhb-community-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/community/communityList.jsp
=> 2020.03.25 14:30 윤희빈 커뮤니티 vo, controller, mapper, list 수정

plzSeatdown/src/main/resources/mappers/review-mapper.xml
=> 2020.03.26 좌석 리뷰 작성 에러 수정

plzSeatdown/src/main/webapp/WEB-INF/views/common/nav.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewUpdate.jsp
=> 2020.03.26 11:20 reviewSeats.jsp 수정 버튼 추가

plzSeatdown/src/main/webapp/WEB-INF/views/admin/comm_report.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/common/nav.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/reply_report.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/review_report.jsp
=> 2020.03.26 서원

plzSeatdown/src/main/java/com/bg/plzSeatdown/websocket/controller/WebChattingController.java, plzSeatdown/src/main/webapp/WEB-INF/views/chat/chattingView.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/index2.jsp, plzSeatdown/src/main/webapp/resources/css/chattingView.css
채팅 프사 추가 date 위치 변경
스크롤 하단 자동 고정 엔터키 이벤트 적용
=> 2020.03.27 서원

plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/DAO/ReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/vo/ReviewImage.java, plzSeatdown/src/main/resources/mappers/review-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/common/nav.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/emailCheckForm.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/signUpComplete.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/signUpForm.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewUpdate.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewWrite.jsp, plzSeatdown/src/main/webapp/resources/css/member-progress.css
=> 2020.03.27 리뷰 수정 삭제, 회원가입 화면 수정

plzSeatdown/src/main/java/com/bg/plzSeatdown/alarm/common/ReplyEchoHandler.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/DAO/ReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/vo/SeatReview.java, plzSeatdown/src/main/resources/mappers/review-mapper.xml, plzSeatdown/src/main/resources/spring/root-context.xml, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp
=> 2020.03.28 12:26 조은희 좋아요 알람 추가

plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/dao/MemberDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/service/MemberService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/service/MemberServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/model/vo/Member.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/controller/MypageController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/model/dao/MypageDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/model/service/MypageService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/mypage/model/service/MypageServiceImpl.java, plzSeatdown/src/main/resources/mappers/member-mapper.xml, plzSeatdown/src/main/resources/mappers/mypage-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/common/header.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/common/nav.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/signUpForm.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/mypage.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewUpdate.jsp
=> 2020.03.28 13:20 헤더,네비 디자인 변경, 리뷰 수정 오탈자 수정

plzSeatdown/src/main/java/com/bg/plzSeatdown/alarm/model/dao/AlarmDAO.java, plzSeatdown/src/main/webapp/WEB-INF/views/common/header.jsp
=> 2020.03.28 13:41 헤더 재업로드

plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/DAO/ReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/vo/ReviewWrite.java, plzSeatdown/src/main/resources/mappers/review-mapper.xml, plzSeatdown/src/main/resources/mybatis-config.xml, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewWrite.jsp, plzSeatdown/src/main/webapp/resources/css/review_write.css
=> 2020.03.28 18:48 리뷰 작성 관련 코드 수정 및 기능 추가

plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/webapp/WEB-INF/views/common/header.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewUpdate.jsp
=> 2020.03.28 리뷰 기능 에러 수정

plzSeatdown/src/main/webapp/WEB-INF/views/community/communityDetail.jsp
=> 2020.03.29 11:25 전지혜 CommunitiDetail.jsp 깃 반영 안된 부분 수정

plzSeatdown/src/main/java/com/bg/plzSeatdown/message/common/MessageEchoHandler.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/message/controller/MessageController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/message/model/dao/MessageDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/message/model/service/MessageService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/message/model/service/MessageServiceImpl.java, plzSeatdown/src/main/resources/mappers/message-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/common/header.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/message/messageDetail.jsp
헤더에 쪽지 알람 기능 추가
쪽지 알람 기능 넣은 message controller, service,
dao, mapper 추가
=> 2020.03.29 서원

plzSeatdown/src/main/webapp/WEB-INF/views/common/header.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/message/receiveList.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/message/sendList.jsp
=> 2020.03.30 서원

plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java, plzSeatdown/src/main/resources/spring/root-context.xml
=> 2020.03.30 회원가입 mapping 수정

plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp, plzSeatdown/src/main/webapp/resources/css/main.css
=> 2020.03.30 메인 css 휠 색상, 리뷰 기능 추가

plzSeatdown/src/main/webapp/WEB-INF/views/community/communityDetail.jsp
=> 2020.03.30 18:55 윤희빈 커뮤니티제발디테일jsp

plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp
=> 2020/03/30 리뷰 좌석 로딩시 깜빡임 ..

plzSeatdown/src/main/java/com/bg/plzSeatdown/login/controller/LoginController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/alarmSetting.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/ask.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/askDetail.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/mycommu.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/mycommu2.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/mypage.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/myreview.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/mypage/myticket.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSideMenu.jsp
=> 2020.03.31 13:43 마이페이지 / reviewSideMenu 수정

plzSeatdown/src/main/webapp/WEB-INF/views/index.jsp
=> 2020.03.31 서원

plzSeatdown/src/main/java/com/bg/plzSeatdown/login/controller/LoginController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/member/controller/MemberController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/DAO/ReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewServiceImpl.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/seat/controller/SeatController.java, plzSeatdown/src/main/resources/mappers/review-mapper.xml
=> 2020.04.01 10:01 로그인, 리뷰 삭제, 좌석부분 일부 수정

plzSeatdown/src/main/webapp/WEB-INF/views/index2.jsp
=> 2020.04.01 서원

plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminCommController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/admin/controller/AdminReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/websocket/common/EchoHandler.java, plzSeatdown/src/main/resources/mappers/admin-community-mapper.xml, plzSeatdown/src/main/resources/mappers/admin-review-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/admin/community/communityList.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/review/reviewList.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/admin/review_report.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/chat/chattingView.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/index2.jsp
베타테스트 시 오류났던 관리자 게시판 기능들 수정
채팅 프로필이미지 오류 수정
=> 2020.04.02 서원

plzSeatdown/src/main/resources/mappers/review-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp
=> 2020.04.02 리뷰 작성 버튼 수정 및 이미지 삭제 수정

plzSeatdown/src/main/java/com/bg/plzSeatdown/review/controller/ReviewController.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/DAO/ReviewDAO.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewService.java, plzSeatdown/src/main/java/com/bg/plzSeatdown/review/model/service/ReviewServiceImpl.java, plzSeatdown/src/main/resources/mappers/review-mapper.xml, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewUpdate.jsp
언니 저는 내일 안나오겠습니다.
제몫까지 힘내주세요. 화이팅
=> 2020.04.02 이미지 삭제 기능 에러 수정

plzSeatdown/src/main/webapp/WEB-INF/views/index.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/member/signUpForm.jsp, plzSeatdown/src/main/webapp/WEB-INF/views/review/reviewSeats.jsp
=> 2020.04.03 서원
